export const MOVIE_REQUEST = "MOVIE_REQUEST";
export const MOVIE_FAIL = "MOVIE_FAIL";
export const MOVIE_SUCCESS = "MOVIE_SUCCESS";

export const SHOWS_REQUEST = "SHOWS_REQUEST";
export const SHOWS_FAIL = "SHOWS_FAIL";
export const SHOWS_SUCCESS = "SHOWS_SUCCESS";

export const DETAILS_REQUEST = "DETAILS_REQUEST";
export const DETAILS_FAIL = "DETAILS_FAIL";
export const DETAILS_SUCCESS = "DETAILS_SUCCESS";

export const REMOVE_DETAILS = "REMOVE_DETAILS";
